name: generate-csv-coingecko

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly on Sundays 00:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate BTC hourly CSV (CoinGecko)
        run: |
          python get_btc_hourly_coingecko.py --months 10 --out btcusdt_1h_10months.csv

      - name: Commit & push CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add btcusdt_1h_10months.csv || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update BTC hourly (10 months) via CoinGecko" || true
            git push
          fi